### PR TITLE
Added .Net 8 support

### LINKED ISSUE #22: Upgrade to .Net 8
Opening this issue to track upgrade to .Net 8

### PR DESCRIPTION
**Pull request by amammes**
Added .Net 8 target
Updated Packages using Nuget
Fixed some Assert warnings
Changed NetCore8583.Test.Util.TestHexCodec.EncodeDecode to private to avoid xUnit1013 warning

closes #22

### CODE REVIEW

**Review by Tochemey — APPROVED** [review]

**Comment by Tochemey** [comment]
@amammes please can you try and run the tests on a linux(ubuntu) env?

**Comment by amammes** [comment]
Sorry, I don't know how to do that

**Comment by Tochemey** [comment]
> Sorry, I don't know how to do that.
> 
> By the way in the VS2022 build output window I see "The package NetCore8583.1.1.0 is missing a readme." Shouldn't the version be 2.1.0? As least that's your latest release

I will take a look this week. Yeah I think it should be `2.1.0`. Let me check that.

**Comment by Tochemey** [comment]
@amammes I have fixed the issues. I am going to merge it and cut a new release tag. Thanks for the PR. I really appreciate it

**Comment by amammes** [comment]
Glad to contribute this PR. Now I just need to learn how to use this library. :)

Do you have any sample projects, I've already checked readme.md, and saw some examples there, but if you had a small project that can process a 100 AUTH message that would be great.

**Pull request merged**
